apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
  namespace: argocd
spec:
  destination:
    namespace: hello
    server: https://kubernetes.default.svc 
  project: hello 
  source: 
    path: p3/conf/hello
    repoURL: https://github.com/viruskizz/42bangkok-inception-of-things
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true