apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: default
spec:
  destination:
    name: ''
    namespace: hello
    server: https://kubernetes.default.svc
  source:
    path: p3/conf/hello
    repoURL: https://github.com/viruskizz/42bangkok-inception-of-things.git
    targetRevision: main
  sources: []
  project: hello
