apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil42
  namespace: argocd
spec:
  project: default
  destination:
    name: ''
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: p3/conf/app
    repoURL: https://github.com/viruskizz/42bangkok-inception-of-things.git
    targetRevision: main
  sources: []
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
