apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil42
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: wil42
  template:
    metadata:
      labels:
        app: wil42
    spec:
      containers:
      - image: wil42/playground:v2
        name: wil42
        ports:
        - containerPort: 80