Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/bionic64"
	config.vm.box_version = "20230607.0.5"
	config.vm.define "sharnvonS" do |master|
		master.vm.hostname = "sharnvonS"
		master.vm.network "private_network", ip: "192.168.56.110"
		master.vm.provider "virtualbox" do |vb|
			vb.name = "sharnvonS"
			vb.memory = 1024
			vb.cpus = 1
		end
		master.vm.provision "file", source: "./confs/sshd_config", destination: "/home/vagrant/sshd_config"
		master.vm.provision "shell", path: "./scripts/master_script.sh"
	end
	config.vm.define "sharnvonSW" do |woker|
		woker.vm.hostname = "sharnvonSW"
		woker.vm.network "private_network", ip: "192.168.56.111"
		woker.vm.provider "virtualbox" do |vb|
			vb.name = "shanvonSW"
			vb.memory = 1024
			vb.cpus = 1
		end
		woker.vm.provision "shell", path: "./scripts/woker_script.sh"
	end
end
