Vagrant.configure("2") do |config|
	config.vm.box = "centos/8"
	config.vm.box_version = "2011.0"
	config.vm.define "sharnvonS" do |master|
		master.vm.hostname = "sharnvonS"
		master.vm.network "private_network", ip: "192.168.56.110"
		master.vm.provider "virtualbox" do |vb|
			vb.name = "sharnvonS"
			vb.memory = 1024
			vb.cpus = 1
		end
		master.vm.provision "shell", path: "./scripts/master_script.sh"
	end
	config.vm.define "sharnvonSW" do |woker|
		woker.vm.hostname = "sharnvonSW"
		woker.vm.network "private_network", ip: "192.168.56.111"
		woker.vm.provider "virtualbox" do |vb|
			vb.name = "shanvonSW"
			vb.memory = 1024
			vb.cpus = 1
		end
		woker.vm.provision "shell", path: "./scripts/woker_script.sh"
	end
end
