apiVersion: v1
kind: Service
metadata:
  name: wil-playground
spec:
  type: NodePort
  # clusterIP: 10.43.0.1
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 8888
  selector:
    app: wil-playground